/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;


import A23.FrmInicio;
import JInternalFrames.A1;
import JInternalFrames.A10;
import JInternalFrames.A11;
import JInternalFrames.A12;
import JInternalFrames.A13;
import JInternalFrames.A14;
import JInternalFrames.A15;
import JInternalFrames.A16;
import JInternalFrames.A17;
import JInternalFrames.A18;
import JInternalFrames.A19;
import JInternalFrames.A2;
import JInternalFrames.A20;
import JInternalFrames.A21;
import JInternalFrames.A22;
import JInternalFrames.A3;
import JInternalFrames.A4;
import JInternalFrames.A5;
import JInternalFrames.A6;
import JInternalFrames.A7;
import JInternalFrames.A8;
import JInternalFrames.A9;
import JInternalFrames.O1;
import JInternalFrames.O10;
import JInternalFrames.O11;
import JInternalFrames.O12;
import JInternalFrames.O13;
import JInternalFrames.O13p2;
import JInternalFrames.O14;
import JInternalFrames.O15;
import JInternalFrames.O16;
import JInternalFrames.O17;
import JInternalFrames.O18;
import JInternalFrames.O19;
import JInternalFrames.O2;
import JInternalFrames.O20;
import JInternalFrames.O3;
import JInternalFrames.O4;
import JInternalFrames.O5;
import JInternalFrames.O6;
import JInternalFrames.O7;
import JInternalFrames.O8;
import JInternalFrames.O9;
import JInternalFrames.T1;
import JInternalFrames.T2;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Rony Stico
 */
public class SesionIniciada4 extends javax.swing.JFrame {

    public void Acercademethod () {
        new Acercade2(this,true).setVisible(true); 
    }
    
    public void Ayudamethod () {
        new Ayuda(this,true).setVisible(true);
    }
    
    /**
     * Creates new form SesionIniciada4
     */
    public SesionIniciada4() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/ImagenesyLibrerias/nuts.jpg"));
        Image image = icon.getImage();
        dskpane = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g) {
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        HerramientasMenu = new javax.swing.JMenu();
        T0 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        A0 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        PDF0 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caja de Herramientas - (Rony Stico)");

        jToolBar1.setFloatable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesyLibrerias/Toolboxicon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Caja de herramientas");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Presiona \"Ayuda\" para saber todo lo que necesitas");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Creado por Rony Stico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jToolBar1.add(jPanel1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesyLibrerias/Ayuda32x32.png"))); // NOI18N
        jButton1.setText("Ayuda");
        jButton1.setToolTipText("Te guía con lo que debes saber para usar esta caja de herramientas");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesyLibrerias/Informacion32x32.png"))); // NOI18N
        jButton2.setText("Acerca de...");
        jButton2.setToolTipText("Aquí están las fuentes y agradecimientos a los que hicieron este programa posible");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesyLibrerias/exit.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.setToolTipText("<html>\n<body>\n<p>Sirve para cerrar todo rastro que tengas abierto de este programa\n<br/>\nRecuerda guardar tus datos antes de salir\n</p>\n</body>\n</html>");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        HerramientasMenu.setForeground(new java.awt.Color(0, 0, 0));
        HerramientasMenu.setText("Herramientas");

        T0.setText("1. Tareas del Tutor");

        jMenuItem1.setText("1. Verificador de Fechas");
        jMenuItem1.setToolTipText("Herramienta para saber si una fecha es correcta...\nAcepta años bisiestos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        T0.add(jMenuItem1);

        jMenuItem2.setText("2. Nómina Salarial");
        jMenuItem2.setToolTipText("<html>\n<body>\n<p>Calcula la nomina salarial neta de unos obreros cuyo trabajo se paga en horas\n<br/>\n<br/>\nEl calculo se realiza de la siguiente manera: \n<br/>\n- Las primeras 35 horas a una tasa fija 50 pesos\n<br/>\n-Las horas extras se calculan: tarifa fija + el 1.5 por ciento de la tarifa fija\n<br/>\n<br/>\nLos impuestos a deducir de los trabajadores varían según el sueldo mensual:\n<br/>\n- Si el sueldo es menos de 20,000, el sueldo es libre de impuestos\n<br/>\n- Al contrario se cobra un 20% de impuestos\n</p>\n<body>\n<html>");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        T0.add(jMenuItem2);

        HerramientasMenu.add(T0);

        A0.setText("2. Curso de Java - Juan Carlos Arcila Díaz");

        jMenuItem4.setText("1. Área del círculo");
        jMenuItem4.setToolTipText("<html>\n<body>\n<p>\nEncuentra el área de un círculo usando la fórmula<br/>\n<br/>\nA= Pi . r^2 donde<br/>\n<br/>\nA = Área del Círculo<br/>\nPi = 3.14159<br/>\nr (radio) = Es el radio del Círculo<br/>\n</p>\n</body>\n</html>");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem4);

        jMenuItem5.setText("2. Potencia");
        jMenuItem5.setToolTipText("<html>\n<body>\n<p>\nHallar la potencia a^n, donde a y n pertenecen a Z^+ (Números enteros positivos);<br/>\nLa base a y el exponente n deben ser ingresados por el usuario\n</p>\n</body>\n</html>");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem5);

        jMenuItem6.setText("3. Promedio");
        jMenuItem6.setToolTipText("<html>\n<body>\n<p>\nIngresa dos notas de un curso académico...\n<br/>\nSe va a calcular y mostrar su promedio\n</p>\n</body>\n</html>");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem6);

        jMenuItem7.setText("4. Ventas");
        jMenuItem7.setToolTipText("<html>\n<body>\n<p>\nIngresar el precio de compra unitario de un Producto,<br/>\nla cantidad de compra de dicho producto; calcular y mostrar<br/>\nel precio parcial (precio unitario * cantidad), el monto del IGV<br/>\nque es el 18% del precio parcial, y el precio neto<br/>\n(precio parcial + Monto del IGV)\n</p>\n</body>\n</html>");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem7);

        jMenuItem8.setText("5. Registro de Usuarios*");
        jMenuItem8.setToolTipText("Herramienta de prueba. Disfruta");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem8);

        jMenuItem9.setText("6. Calcular Interés");
        jMenuItem9.setToolTipText("<html>\n<body>\n<p>\nCalcular el interés compuesto generado por un capital depositado durante cierta cantidad de tiempo<br/>\na una tasa de interés determinada, la fórmula es la siguiente: <br/>\n<br/>\nM= (1+r%)^t . C <br/>\nI=M-C<br/>\n<br/>\nM (Monto) = Suma del capital más intereses producidos en un tiempo determinado<br/>\nr (Taza de Interés) = Ganancia que se obtiene por cada 100 unidades monetarias en cada período de tiempo<br/>\nT (Tiempo) = Período de tiempo durante el cual se cede el capital<br/>\nC (Capital) = Dinero invertido para generar una ganancia<br/>\nI (Interés) = Utilidad generada \n</p>\n</body>\n</html>");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem9);

        jMenuItem10.setText("7. Calcular Descuento");
        jMenuItem10.setToolTipText("<html>\n<body>\n<p>\nHacer un aplicación que permita ingresar el precio unitario de un producto vendido,<br/>\nla cantidad de venta; después calcular el precio parcial (precio unitario * cantidad), <br/>\naplicar un descuento del 7 % sólo si el precio parcial es mayor que  $. 150, <br/>\nal final mostrar también el precio neto (precio parcial – descuento).<br/>\n</p>\n</body>\n</html>");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem10);

        jMenuItem11.setText("8. Promedio de Notas");
        jMenuItem11.setToolTipText("<html>\n<body>\n<p>\nHacer un programa en java que permita ingresar tres notas para un alumno, <br/>\nla nota A que tiene una importancia de 3 créditos, la nota B tiene 4 Créditos, y <br/>\nla nota C tiene sólo 2 créditos; se debe de calcular el promedio teniendo en cuenta las notas <br/>\ny al final si el alumno tiene un promedio igual o mayor a 10.5 mostrar “Aprobado”, <br/>\nen caso contrario “Desaprobado”.\n</p>\n</body>\n</html>");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem11);

        jMenuItem12.setText("9. Utilidad por años");
        jMenuItem12.setToolTipText("<html>\n<body>\n<p>\nCalcular la utilidad que un trabajador recibe en el reparto de utilidades, si a este se le asigna<br/>\ncomo un porcentaje de su salario mensual que depende de su antigüedad en la empresa<br/>\nde acuerdo con lo siguiente:<br/>\n<br/>\nMenos de un año: 5% del salario<br/>\n1 año o más, pero menos de 2 años: 7% del salario<br/>\n2 años o más, pero menos de 5 años: 10% del salario<br/>\n5 años o más, pero menos de 10 años: 15% del salario<br/>\n10 años o más: 20% del salario<br/>\n</p>\n</body>\n</html>");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem12);

        jMenuItem13.setText("10. Día de la semana");
        jMenuItem13.setToolTipText("<html>\n<body>\n<p>\n Ingresar un número por teclado y determinar su representación en un día de la semana.<br/>\n<br/>\nPor ejemplo si se ingresa 3 deberá mostrar miércoles, si se ingresa 7 deberá mostrar domingo.<br/>\nSi se ingresa un número fuera del rango entre 1 y 7 mostrar el mensaje \"Error intente con un nuevo número\".\n</p>\n</body>\n</html>");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem13);

        jMenuItem14.setText("11. Promedio de Notas 2");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem14);

        jMenuItem15.setText("12. Tabla Aritmética");
        jMenuItem15.setToolTipText("<html>\n<body>\n<p>\nHacer un programa en java que permita mostrar la tabla de sumar, restar, multiplicar y dividir<br/>\nde un número igresado previamente\n</p>\n</body>\n</html>");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem15);

        jMenuItem16.setText("13. Promedio de Notas 3");
        jMenuItem16.setToolTipText("<html>\n<body>\n<p>\nHacer un programa en java que permita validar el ingreso de notas (0-20) para “n” <br/>\nalumnos, es decir mientras la nota este fuera de ese rango el programa deberá indicar<br/>\nal usuario ingresar la nota, hasta que se ingrese la nota correcta; al final mostrar el promedio.\n</p>\n</body>\n</html>");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem16);

        jMenuItem17.setText("14. Reparto de Vacunas");
        jMenuItem17.setToolTipText("<html>\n<body>\n<p>\nUna organización tiene punto de repartos de vacunas, cada día se registra con cuantas vacunas se inicia. <br/>\nCrear un programa en java que gestione las entregas (validar que la cantidad a entregar no sea mayor que el stock) <br/>\n y de un aviso cuando el stock es inferior a 10 unidades.\n<p/>\n<body/>\n<html/>");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem17);

        jMenuItem18.setText("15. Promedio de Notas 4*");
        jMenuItem18.setToolTipText("<html>\n<body>\n<p>\nImplementar un vector para almacenar las notas del curso de matemática de 7 alumnos;<br/>\nal final mostrar el promedio de esas notas.\n<p/>\n<body/>\n<html/>");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem18);

        jMenuItem19.setText("16. Promedio de Gastos");
        jMenuItem19.setToolTipText("<html>\n<body>\n<p>\nImplementar un programa que permita gestionar los gastos de los “n” días de una persona,<br/>\n los gastos se deben de ingresar con un inputBox; al final se deberá mostrar el total de gastos <br/>\n y que día se hizo el mayor gasto.\n<p/>\n<body/>\n<html/>");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem19);

        jMenuItem20.setText("17. Stock de Restaurante");
        jMenuItem20.setToolTipText("<html>\n<body>\n<p>\n Implementar una programa para registrar los datos de venta de un restaurant, <br/>\nse debe almacenar en una matriz el nombre del plato, su precio, y la cantidad disponible.<br/>\nEl programa permitirá realizar búsquedas por el nombre del plato, si existe el plato buscado nos<br/> mostrará su precio y la cantidad disponible para vender, el stock se debe de actualizar por cada venta.\n<p/>\n<body/>\n<html/>");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem20);

        jMenuItem21.setText("18. Utilidades para Textos");
        jMenuItem21.setToolTipText("<html>\n<body>\n<p>\nIngresa cualquier texto y se mostrará ese mismo texto en mayúsculas, minúsculas entre otros\n<p/>\n<body/>\n<html/>");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem21);

        jMenuItem22.setText("19. Cálculos Básicos");
        jMenuItem22.setToolTipText("<html>\n<body>\n<p>\nSuma, Resta, Multiplica y Divide dos números que ingreses. Es todo\n<p/>\n<body/>\n<html/>");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem22);

        jMenuItem23.setText("20. Gestión de Banco");
        jMenuItem23.setToolTipText("<html>\n<body>\n<p>\nDiseñar y programar una aplicación que permita gestionar los retiros y depósitos de <br/>\nla cuenta bancaria de un cliente. Se debe primero gestionar los datos del cliente <br/>\ny cuál es el monto de apertura de la cuenta de ahorros.\n<p/>\n<body/>\n<html/>");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem23);

        jMenuItem24.setText("21. Prueba de JClass*");
        jMenuItem24.setToolTipText("<html>\n<body>\n<p>\nHerramienta de prueba. Disfruta o abre otra herramienta más útil\n<p/>\n<body/>\n<html/>");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem24);

        jMenuItem25.setText("22. Registro en Empresa");
        jMenuItem25.setToolTipText("<html>\n<body>\n<p>\nPrograma que registra en una empresa a un cliente o empleado y le dice su sueldo en base<br/>\na su contrato.<br/>\nEl sueldo base es 750.<br/> \nSi el contrato es C el sueldo será el sueldo base más 350<br/>\nSi es N el sueldo será igual al sueldo base más 750<br/>\n<br/>\nResumen<br/>\n<br/>\nSi el contrato es C = 750+350<br/>\nSi el contrato es N = 750+750<br/>\n<p/>\n<body/>\n<html/>");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem25);

        jMenuItem26.setText("23. Ingresos y Salidas*");
        jMenuItem26.setToolTipText("<html>\n<body>\n<p>\nHerramienta de prueba. Disfruta o abre otra herramienta más útil\n<p/>\n<body/>\n<html/>");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        A0.add(jMenuItem26);

        HerramientasMenu.add(A0);

        PDF0.setText("3. Fundación Código Libre Dominicano");

        jMenuItem27.setText("1. Selecciona Animales*");
        jMenuItem27.setToolTipText("<html>\n<body>\n<p>\nSelecciona varios animales y se muestran los que hayas seleccionado\n<p/>\n<body/>\n<html/>\n");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem27);

        jMenuItem28.setText("2. Selecciona un Color*");
        jMenuItem28.setToolTipText("<html>\n<body>\n<p>\nSelecciona UN color y se muestra justo debajo el resultado\n<p/>\n<body/>\n<html/>\n");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem28);

        jMenuItem29.setText("3. Cuadros de Lista*");
        jMenuItem29.setToolTipText("<html>\n<body>\n<p>\nSólo da clic en un color y aparecerá justo debajo\n<p/>\n<body/>\n<html/>\n");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem29);

        jMenuItem30.setText("4. Cuadros Combinados*");
        jMenuItem30.setToolTipText("<html>\n<body>\n<p>\nSelecciona un color predeterminado o escribe el que desees en el cuadro y aparecerá<br/>\njusto debajo\n<p/>\n<body/>\n<html/>\n");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem30);

        jMenuItem31.setText("5. Toggle Buttons");
        jMenuItem31.setToolTipText("<html>\n<body>\n<p>\nEres dueño/a de un hotel y luego de que ingreses un precio base hay unos botones donde<br/>\neliges más costos predeterminados para tu próximo cliente y justo debajo aparecerá el resultado<br/>\nNota: Los precios tienen ícono de Euros\n<p/>\n<body/>\n<html/>\n");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem31);

        jMenuItem32.setText("6. Sliders");
        jMenuItem32.setToolTipText("<html>\n<body>\n<p>\nDesliza una ¨pelota¨ dentro de una barra e irá apareciendo su resultado instantáneamente\n<p/>\n<body/>\n<html/>");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem32);

        jMenuItem33.setText("7. Spinner*");
        jMenuItem33.setToolTipText("<html>\n<body>\n<p>\nTambién caí redondito cuando pensé que era un Spinner de los que se le da vueltas<br/>\nEs sólo un Spinner de Java, puedes abrir otra herramienta más útil\n<p/>\n<body/>\n<html/>\n");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem33);

        jMenuItem34.setText("8. Barra de Desplazamiento");
        jMenuItem34.setToolTipText("<html>\n<body>\n<p>\nParecido al Slider. Desliza una ¨pelota¨ dentro de una barra y te dirá el resultado instantáneamente\n<p/>\n<body/>\n<html/>\n");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem34);

        jMenuItem35.setText("9. Barra de Menus*");
        jMenuItem35.setToolTipText("<html>\n<body>\n<p>\nOtra herramienta de prueba. Sólo puedes cambiar el color de fondo dentro del menú ¨Edición¨\n<p/>\n<body/>\n<html/>\n");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem35);

        jMenuItem36.setText("10. Barra de Herramientas*");
        jMenuItem36.setToolTipText("<html>\n<body>\n<p>\nSólo funcionan los botones dentro de la barra de herramientas como dice el título\n<p/>\n<body/>\n<html/>\n");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem36);

        jMenuItem37.setText("11. Menus Emergentes*");
        jMenuItem37.setToolTipText("<html>\n<body>\n<p>\nSi haces clic en cualquier sitio tendrás una sorpresita\n<p/>\n<body/>\n<html/>\n");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem37);

        jMenuItem38.setText("12. Seleccionar Archivo");
        jMenuItem38.setToolTipText("<html>\n<body>\n<p>\nHerramienta que te permite seleccionar un archivo de tu computador y te muestra su ubicación exacta\n<p/>\n<body/>\n<html/>\n");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem38);

        jMenuItem39.setText("13. Paneles de Desplazamiento*");
        jMenuItem39.setToolTipText("<html>\n<body>\n<p>\nHerramienta que ajusta un contenido muy grande en una ventana muy pequeña\n<p/>\n<body/>\n<html/>\n");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem39);

        jMenuItem40.setText("14. Paneles de Desplazamiento 2*");
        jMenuItem40.setToolTipText("<html>\n<body>\n<p>\nAl igual que la herramienta de arriba<br/>\nHerramienta que ajusta un contenido muy grande en una ventana muy pequeña\n<p/>\n<body/>\n<html/>\n");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem40);

        jMenuItem41.setText("15. Parqueo");
        jMenuItem41.setToolTipText("<html>\n<body>\n<p>\nAhora eres dueño/a de un parqueo. Esta herramienta sirve para que cuentes los autos<br/>\nque entran y salen\n<p/>\n<body/>\n<html/>\n");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem41);

        jMenuItem42.setText("16. Calculadora Básica");
        jMenuItem42.setToolTipText("<html>\n<body>\n<p>\nCalculadora muy básica. Sólo sabe sumar y restar\n<p/>\n<body/>\n<html/>\n");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem42);

        jMenuItem43.setText("17. BorderLayout*");
        jMenuItem43.setToolTipText("<html>\n<body>\n<p>\nHerramienta de prueba. Disfruta o abre otra herramienta más útil\n<p/>\n<body/>\n<html/>");
        jMenuItem43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem43);

        jMenuItem44.setText("18. Distribución de Paneles*");
        jMenuItem44.setToolTipText("<html>\n<body>\n<p>\nHerramienta de prueba. Disfruta o abre otra herramienta más útil\n<p/>\n<body/>\n<html/>");
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem44);

        jMenuItem45.setText("19. Calcular Artículos");
        jMenuItem45.setToolTipText("<html>\n<body>\n<p>\nHerramienta que te permite calcular el precio de una o varias unidades de un artículo<br/>\nPuedes configurar los Porcientos (%) de descuento y de impuestos que desees\n<p/>\n<body/>\n<html/>\n");
        jMenuItem45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem45ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem45);

        jMenuItem46.setText("20. Modelos de Cuadro*");
        jMenuItem46.setToolTipText("<html>\n<body>\n<p>\nSólo muestra varios nombres y cuando haces clic en un nombre se muestra en otra parte\n<p/>\n<body/>\n<html/>\n");
        jMenuItem46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem46ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem46);

        jMenuItem47.setText("21. Pares e Impares*");
        jMenuItem47.setToolTipText("<html>\n<body>\n<p>\nPuedes pedir que muestre números pares e impares\n<p/>\n<body/>\n<html/>\n");
        jMenuItem47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem47ActionPerformed(evt);
            }
        });
        PDF0.add(jMenuItem47);

        HerramientasMenu.add(PDF0);

        menuBar.add(HerramientasMenu);

        helpMenu.setForeground(new java.awt.Color(0, 0, 0));
        helpMenu.setText("Ayuda y Opciones");
        helpMenu.setToolTipText("Te guía con lo que debes saber para usar esta caja de herramientas ");

        contentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesyLibrerias/Ayuda32x32.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Ayuda");
        contentMenuItem.setToolTipText("Te guía con lo que debes saber para usar esta caja de herramientas ");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesyLibrerias/Informacion32x32.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de...");
        aboutMenuItem.setToolTipText("Aquí están las fuentes y agradecimientos a los que hicieron este programa posible");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesyLibrerias/salir32x32.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.setToolTipText("<html>\n<body>\n<p>Sirve para cerrar todo rastro que tengas abierto de este programa\n<br/>\nRecuerda guardar tus datos antes de salir\n</p>\n</body>\n</html>");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(exitMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addComponent(dskpane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dskpane, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        T1 t1 = new T1();
        dskpane.add(t1);
        t1.toFront();
        t1.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        T2 t2 = new T2();
        dskpane.add(t2);
        t2.toFront();
        t2.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
       Acercademethod();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        A1 a1 = new A1();
        dskpane.add(a1);
        a1.toFront();
        a1.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        A2 a2 = new A2();
        dskpane.add(a2);
        a2.toFront();
        a2.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        A3 a3 = new A3();
        dskpane.add(a3);
        a3.toFront();
        a3.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        A4 a4 = new A4();
        dskpane.add(a4);
        a4.toFront();
        a4.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        A5 a5 = new A5();
        dskpane.add(a5);
        a5.toFront();
        a5.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        A6 a6 = new A6();
        dskpane.add(a6);
        a6.toFront();
        a6.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        A7 a7 = new A7();
        dskpane.add(a7);
        a7.toFront();
        a7.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        A8 a8 = new A8();
        dskpane.add(a8);
        a8.toFront();
        a8.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       A9 a9 = new A9();
        dskpane.add(a9);
        a9.toFront();
        a9.show();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        A10 a10 = new A10();
        dskpane.add(a10);
        a10.toFront();
        a10.show();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        A11 a11 = new A11();
        dskpane.add(a11);
        a11.toFront();
        a11.show();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        A12 a12 = new A12();
        dskpane.add(a12);
        a12.toFront();
        a12.show();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        A13 a13 = new A13();
        dskpane.add(a13);
        a13.toFront();
        a13.show();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        A14 a14 = new A14();
        dskpane.add(a14);
        a14.toFront();
        a14.show();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        A15 a15 = new A15();
        dskpane.add(a15);
        a15.toFront();
        a15.show();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        A16 a16 = new A16();
        dskpane.add(a16);
        a16.toFront();
        a16.show();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        A17 a17 = new A17();
        dskpane.add(a17);
        a17.toFront();
        a17.show();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        A18 a18 = new A18();
        dskpane.add(a18);
        a18.toFront();
        a18.show();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        A19 a19 = new A19();
        dskpane.add(a19);
        a19.toFront();
        a19.show();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        A20 a20 = new A20();
        dskpane.add(a20);
        a20.toFront();
        a20.show();
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        A21 a21 = new A21();
        dskpane.add(a21);
        a21.toFront();
        a21.show();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        A22 a22 = new A22();
        dskpane.add(a22);
        a22.toFront();
        a22.show();
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        FrmInicio a23 = new FrmInicio();
        a23.setVisible(true);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        O1 o1 = new O1();
        dskpane.add(o1);
        o1.toFront();
        o1.show();
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        O2 o2 = new O2();
        dskpane.add(o2);
        o2.toFront();
        o2.show();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        O3 o3 = new O3();
        dskpane.add(o3);
        o3.toFront();
        o3.show();
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        O4 o4 = new O4();
        dskpane.add(o4);
        o4.toFront();
        o4.show();
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        O5 o5 = new O5();
        dskpane.add(o5);
        o5.toFront();
        o5.show();
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        O6 o6 = new O6();
        dskpane.add(o6);
        o6.toFront();
        o6.show();
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        O7 o7 = new O7();
        dskpane.add(o7);
        o7.toFront();
        o7.show();
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        O8 o8 = new O8();
        dskpane.add(o8);
        o8.toFront();
        o8.show();
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        O9 o9 = new O9();
        dskpane.add(o9);
        o9.toFront();
        o9.show();
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        O10 o10 = new O10();
        dskpane.add(o10);
        o10.toFront();
        o10.show();
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        O11 o11 = new O11();
        dskpane.add(o11);
        o11.toFront();
        o11.show();
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        O12 o12 = new O12();
        dskpane.add(o12);
        o12.toFront();
        o12.show();
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        O13 o13 = new O13();
        dskpane.add(o13);
        o13.toFront();
        o13.show();
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
      O14 o14 = new O14();
        dskpane.add(o14);
        o14.toFront();
        o14.show(); 
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        O15 o15 = new O15();
        dskpane.add(o15);
        o15.toFront();
        o15.show();
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem43ActionPerformed
        O16 o16 = new O16();
        dskpane.add(o16);
        o16.toFront();
        o16.show();
    }//GEN-LAST:event_jMenuItem43ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        O13p2 o13p2 = new O13p2();
        dskpane.add(o13p2);
        o13p2.toFront();
        o13p2.show();
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44ActionPerformed
        O17 o17 = new O17();
        dskpane.add(o17);
        o17.toFront();
        o17.show();
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void jMenuItem45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem45ActionPerformed
        O18 o18 = new O18();
        dskpane.add(o18);
        o18.toFront();
        o18.show();
    }//GEN-LAST:event_jMenuItem45ActionPerformed

    private void jMenuItem46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem46ActionPerformed
        O19 o19 = new O19();
        dskpane.add(o19);
        o19.toFront();
        o19.show();
    }//GEN-LAST:event_jMenuItem46ActionPerformed

    private void jMenuItem47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem47ActionPerformed
        O20 o20 = new O20();
        dskpane.add(o20);
        o20.toFront();
        o20.show();
    }//GEN-LAST:event_jMenuItem47ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ayudamethod();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Acercademethod();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        Ayudamethod();
    }//GEN-LAST:event_contentMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SesionIniciada4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SesionIniciada4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SesionIniciada4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SesionIniciada4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SesionIniciada4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu A0;
    private javax.swing.JMenu HerramientasMenu;
    private javax.swing.JMenu PDF0;
    private javax.swing.JMenu T0;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane dskpane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ImagenesyLibrerias/Toolboxicon.png")));
    }

}
