/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Perro;

/**
 *
 * @author Rony Stico
 */
public class FrmPOO extends javax.swing.JFrame {

    /**
     * Creates new form FrmPOO
     */
    public FrmPOO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btno1 = new javax.swing.JButton();
        btno2 = new javax.swing.JButton();
        btno3 = new javax.swing.JButton();
        txtmensaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prueba de JClass");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("POO"));

        btno1.setText("Objeto 1");
        btno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btno1ActionPerformed(evt);
            }
        });

        btno2.setText("Objeto 2");
        btno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btno2ActionPerformed(evt);
            }
        });

        btno3.setText("Objeto 3");
        btno3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btno3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btno3)
                    .addComponent(btno2)
                    .addComponent(btno1))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtmensaje)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btno1)
                .addGap(18, 18, 18)
                .addComponent(btno2)
                .addGap(18, 18, 18)
                .addComponent(btno3)
                .addGap(18, 18, 18)
                .addComponent(txtmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btno3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btno3ActionPerformed
        Perro perrito = new Perro("Peluchín","Poodle","0.50 cm");
        
        String mensaje = perrito.comer("Pavita");
        txtmensaje.setText(mensaje);
    }//GEN-LAST:event_btno3ActionPerformed

    private void btno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btno1ActionPerformed
        Perro perrito = new Perro();
        perrito.nombre="Chizu";
        perrito.raza="Pastor Alemán";
        perrito.altura="0.70";
        
        String mensaje=perrito.comer("Pollo");
        txtmensaje.setText(mensaje);
        
    }//GEN-LAST:event_btno1ActionPerformed

    private void btno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btno2ActionPerformed
        Perro perrito2 = new Perro();
        perrito2.nombre="Lazy";
        perrito2.altura="0.60";
        
        String mensaje=perrito2.comer("Pan");
        txtmensaje.setText(mensaje);
    }//GEN-LAST:event_btno2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPOO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btno1;
    private javax.swing.JButton btno2;
    private javax.swing.JButton btno3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtmensaje;
    // End of variables declaration//GEN-END:variables
}
