/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JInternalFrames;

/**
 *
 * @author Rony Stico
 */
public class O16 extends javax.swing.JInternalFrame {

    /**
     * Creates new form O16
     */
    public O16() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Border Layout");

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, java.awt.BorderLayout.PAGE_END);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, java.awt.BorderLayout.CENTER);

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Este es un BorderLayout, prueba a agrandar la ventana");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jButton6.setText("jButton6");
        getContentPane().add(jButton6, java.awt.BorderLayout.LINE_START);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
